[package]
name = "keylogger"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
slint = { version = "1.15.1" }
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "json"] }
tracing = "0.1.44"
tokio = { version = "1.49.0", features = ["rt", "rt-multi-thread", "macros", "signal"] }
sqlx = { version = "0.9", features = ["sqlite", "postgres", "migrate", "runtime-tokio", "chrono"] }
futures-util = "0.3.32"
ksni = { version = "0.3" }
tokio-util = "0.7.18"
ed25519-dalek = { version = "3.0.0-rc.1", features = ["rand_core"] }
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0.13.4", features = ["json"] }
base64 = "0.22.1"
axum = { version = "0.8.9", features = ["macros"] }
thiserror = "2"
tower-http = { version = "0.7.0", features = ["trace", "catch-panic", "decompression-gzip"] }
serde_json = "1.0.149"
rand = "0.10.1"
hex = "0.4.3"
flate2 = "1.1.9"
postcard = { version = "1", features = ["alloc"] }
zstd = "0.13.3"
evdevil = { version = "0.5.0", features = ["tokio"] }
libc = "0.2"
nix = { version = "0.31", features = ["time"] }
chrono = "0.4"
niri-ipc = "=25.11.0"

[build-dependencies]
slint-build = "1.15.1"